# language: node_js
# node_js:
# - '8'
# cache:
#   npm: true
#   directories:
#     - node_modules
# install:
#   - npm install
# script:
#   - npm run test
# before_deploy:
#   - npm run build
# deploy:
#   provider: s3
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   bucket: $S3_BUCKET
#   region: 'us-west-1'
#   skip_cleanup: true
#   local-dir: ./build
#   on:
#     branch: master